  commandOption: run
  image: ${bamboo.artifactory_docker}/${bamboo.inject.python_image_to_run}
  detach: 'true'
  name: python-pip-uvicorn
  containerPort_0: '80'
  hostPort_0: '8080'
  serviceWait: 'true'
  serviceUrlPattern: http://localhost:${docker.port}/docs
  serviceTimeout: '30'
  link: 'false'
  workDir: /srv/${bamboo.shortPlanName}
